### PR TITLE
Update data

### PR DESCRIPTION
**Pull request by kylon**

### CODE REVIEW

**Comment by vit9696** [comment]
Hey, does it change anything in regenerated `.c` code?

**Comment by Andrey1970AppleLife** [comment]
MemoryFormFactor:
0x09 DIMM, 0x0D SODIMM
DIMM - desktop
SODIMM - notebook
You changed on MPs 0xD, it is not right, there has to be 0x9.

**Comment by kylon** [comment]
> Hey, does it change anything in regenerated `.c` code?

I think yes, not sure
Are the changes ok? (Apart the MemoryFormFactor)


> MemoryFormFactor:
> 0x09 DIMM, 0x0D SODIMM
> DIMM - desktop
> SODIMM - notebook
> You changed on MPs 0xD, it is not right, there has to be 0x9.

Ops, i had them inverted 0x9 notebook, 0xD desktop
i will fix them

**Comment by vit9696** [comment]
`CPU` list should really conform to `ProcessorType` where possible, and I am not sure whether the GPU/memory names actually conform to some standard format. Other than that it makes some good sense to me, and we will probably merge it right after today `0.0.2` release.

Also, I am not sure whether missing `FirmwareFeatures` is handled correctly but the python tool at the moment.

**Comment by kylon** [comment]
yeah, the python tool does not like missing FirmwareFeatures, i will add define, what is a default value for them?

**Comment by vit9696** [comment]
Actually I am not sure whether any modern Mac can live without `FirmwareFeatures`. Perhaps we should update the tool to set 0 in this case…

**Comment by kylon** [comment]
afaik it is missing in older macs.

mmh, if it is now required, maybe the best thing is to add it back as 0 for those models so that FirmwareFeatures will remain a required field.

**Comment by vit9696** [comment]
I do not believe Apple added it to older Macs, so design-wise the DataBase should not contain them. It is the matter of interpretation on what we provide based on the data, but at least on yaml they clearly should not exist.

**Comment by kylon** [comment]
Here is the output of the script.

Please do note that my script is not so flexible, it s just a big batch tool that creates all the missing files, so changes can be done now and not then.

Already existent files are untouched.

**Comment by Andrey1970AppleLife** [comment]
You have there a problem in OEMStrings:.
Here one of many: https://github.com/acidanthera/MacInfoPkg/pull/3/files#diff-ddb15e9e63e696557993381ba05afbbdR78 So should not be.

In real Macmini SODIMM as for laptops is used. Correct 0xD

**Comment by kylon** [comment]
Thanks

i can squash the commits when we are done if you want.

**Comment by vit9696** [comment]
Please ensure that everything builds first as described in the instruction:
https://github.com/acidanthera/MacInfoPkg#improving-database
Currently it does not, and I clearly cannot merge this.

Other than that, there following issues must be addressed:
- Currently at least `PlatformFeatures` is all wrong, and as a result the `.c` file fails to generate (it must be missing, not "" when unused, and I believe it is used in many places you have "") .
- `BIOSVersion` must be equal to `BIOSLegacyVersion` when legacy format is used, not empty
- `ProcessorType` should follow CPU names, please consider at least trying to fix that (and/or add FIXME).

Thanks to git squashing is done automatically at merge, no need to bother with such nuances.

**Comment by Andrey1970AppleLife** [comment]
@kylon 
Deleting for **PlatformFeature** and **BoardRevision** is authorized. If these parameters are absent in real Mac.

**Comment by vit9696** [comment]
@kylon something is broken with your latest commit. You accidentally killed most of the CPUs in every database entry, please fix that.

**Comment by kylon** [comment]
It was intentional, i ll try to speculate other types.

Do you want something 1:1 or no duplicates in processorType?

**Comment by vit9696** [comment]
This has always been meant to be 1:1. I.e. the CPU list matches ProcessorType. I very well understand that it is not possible to know what CPU ProcessorType matches some CPU model, in this case having some value (potentially sensible, but not required) with a FIXME that it is not reliable. Like this:

```
ProcessorType:
  - 0xA123
  - 0x2134 #FIXME: Needs checking
CPU:
  - Intel Abcdef CPU 1.17 GHz something
  - Intel Abcdef CPU 2.17 GHz something
```

**Comment by Andrey1970AppleLife** [comment]
OEMStrings: "" It is not allowed. At you this mistake in some models is more older 2012. update_generated.py does not check is more older 2012, but it is necessary to correct in any cases.

**Comment by kylon** [comment]
> OEMStrings: "" It is not allowed. At you this mistake in some models is more older 2012. update_generated.py does not check is more older 2012, but it is necessary to correct in any cases.

Thanks, so should i remove that for those who don t have oem string? even if > 2012

**Comment by vit9696** [comment]
The tool will handle this for the time being, and currently OEMStrings are used only for reference purposes. To be honest, I think that this change already provides enough benefit to be merged.

I suggest us do the following:
- merge the changes as they are squashing commits
- provide updates to OEMStrings/other fields based on FirmwarePackages of the old macOS installations in som future.

If there are no objections I will merge it later this evening or maybe tomorrow.

@kylon, firmwares that do not have OEMStrings I think do not exist. Question is whether they actually contain empty string (or maybe space) or some other data.

**Pull request merged**
